image: python:stretch

before_script:
   ##
   ## Install ssh-agent if not already installed, it is required by Docker.
   ## (change apt-get to yum if you use an RPM-based image)
   ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install python3 python3-pip openssh-client -y )'
   ##
   ## Run ssh-agent (inside the build environment)
   ##
  - eval $(ssh-agent -s)
   ##
   ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
   ## We're using tr to fix line endings which makes ed25519 keys work
   ## without extra base64 encoding.
   ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
   ##
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
   ##
   ## Create the SSH directory and give it the right permissions
   ##
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
   ##
  ## Alternatively, use ssh-keyscan to scan the keys of your private server.
  ## Replace example.com with your private server's domain name. Repeat that
  ## command if you have more than one server to connect to.
  ##
  - ssh-keyscan system02.physik.uni-wuerzburg.de >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - pip3 install pdoc3
    - python3 setup.py install
    - pdoc --html heuslertools --template-dir doc/templates
    - scp html/heuslertools/* gitlab@system02.physik.uni-wuerzburg.de:/var/www/cdnep3/heuslertools/
